import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Share,
} from 'react-native';
import { useSelector } from 'react-redux';
import { Ionicons } from '@expo/vector-icons';
import { Picker } from '@react-native-picker/picker';
import { Card, Header, Badge } from '../../components/common';
import { COLORS, SIZES, SHADOWS } from '../../constants/theme';
import { API_CONFIG } from '../../constants';

const CustomerAMCReportScreen = ({ navigation }) => {
  const { token } = useSelector((state) => state.auth);
  const [loading, setLoading] = useState(false);
  const [customers, setCustomers] = useState([]);
  const [selectedCustomer, setSelectedCustomer] = useState('');
  const [reportData, setReportData] = useState(null);
  const [activeTab, setActiveTab] = useState('summary'); // summary, services, callbacks, repairs, materials

  useEffect(() => {
    fetchCustomers();
  }, []);

  const fetchCustomers = async () => {
    try {
      const response = await fetch(`${API_CONFIG.BASE_URL}/customers`, {
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const data = await response.json();
        setCustomers(data);
        if (data.length > 0) {
          setSelectedCustomer(data[0].id);
        }
      }
    } catch (error) {
      console.error('Error fetching customers:', error);
    }
  };

  const generateReport = async () => {
    if (!selectedCustomer) {
      Alert.alert('Error', 'Please select a customer');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch(
        `${API_CONFIG.BASE_URL}/reports/customer-amc-period/${selectedCustomer}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
        }
      );

      if (response.ok) {
        const data = await response.json();
        setReportData(data);
        setActiveTab('summary');
      } else {
        const error = await response.json();
        Alert.alert('Error', error.detail || 'Failed to generate report');
      }
    } catch (error) {
      console.error('Error generating report:', error);
      Alert.alert('Error', 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const shareReport = async () => {
    if (!reportData) return;

    try {
      const message = `
${reportData.customer_info.customer_name} - AMC Period Report

Period: ${reportData.amc_details.start_date} to ${reportData.amc_details.end_date}
Completion: ${reportData.amc_details.period_completion_pct}%

Services: ${reportData.summary.services_completed}/${reportData.summary.services_scheduled}
Callbacks: ${reportData.summary.callbacks_total}
Repairs: ${reportData.summary.repairs_total}
Materials Cost: ${reportData.summary.total_materials_cost}

Customer Rating: ${reportData.summary.customer_rating_avg}/5.0

Generated by LegendLift
      `.trim();

      await Share.share({ message });
    } catch (error) {
      console.error('Error sharing report:', error);
    }
  };

  const exportToPDF = () => {
    Alert.alert('PDF Export', 'PDF export feature will be implemented soon');
    // TODO: Implement PDF generation
  };

  const exportToExcel = () => {
    Alert.alert('Excel Export', 'Excel export feature will be implemented soon');
    // TODO: Implement Excel generation
  };

  const renderSummaryTab = () => (
    <ScrollView>
      {/* AMC Details Card */}
      <Card style={styles.card}>
        <Text style={styles.cardTitle}>AMC Contract Details</Text>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Period:</Text>
          <Text style={styles.value}>
            {reportData.amc_details.start_date} to {reportData.amc_details.end_date}
          </Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Days Elapsed:</Text>
          <Text style={styles.value}>
            {reportData.amc_details.days_elapsed} / {reportData.amc_details.total_days} days
            ({reportData.amc_details.period_completion_pct}%)
          </Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Days Remaining:</Text>
          <Text style={styles.value}>{reportData.amc_details.days_remaining} days</Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>AMC Amount:</Text>
          <Text style={styles.value}>{reportData.amc_details.amc_amount}</Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Amount Received:</Text>
          <Text style={styles.valueSuccess}>{reportData.amc_details.amount_received}</Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Amount Pending:</Text>
          <Text style={styles.valueError}>{reportData.amc_details.amount_pending}</Text>
        </View>
      </Card>

      {/* Summary Statistics Grid */}
      <View style={styles.statsGrid}>
        <View style={[styles.statCard, { backgroundColor: COLORS.primaryLight }]}>
          <Ionicons name="checkmark-circle" size={32} color={COLORS.success} />
          <Text style={styles.statValue}>{reportData.summary.services_completed}</Text>
          <Text style={styles.statLabel}>Completed</Text>
        </View>

        <View style={[styles.statCard, { backgroundColor: COLORS.warningLight }]}>
          <Ionicons name="time" size={32} color={COLORS.warning} />
          <Text style={styles.statValue}>{reportData.summary.services_pending}</Text>
          <Text style={styles.statLabel}>Pending</Text>
        </View>

        <View style={[styles.statCard, { backgroundColor: COLORS.errorLight }]}>
          <Ionicons name="alert-circle" size={32} color={COLORS.error} />
          <Text style={styles.statValue}>{reportData.summary.services_overdue}</Text>
          <Text style={styles.statLabel}>Overdue</Text>
        </View>

        <View style={[styles.statCard, { backgroundColor: COLORS.infoLight }]}>
          <Ionicons name="call" size={32} color={COLORS.info} />
          <Text style={styles.statValue}>{reportData.summary.callbacks_total}</Text>
          <Text style={styles.statLabel}>Callbacks</Text>
        </View>

        <View style={[styles.statCard, { backgroundColor: COLORS.secondaryLight }]}>
          <Ionicons name="construct" size={32} color={COLORS.secondary} />
          <Text style={styles.statValue}>{reportData.summary.repairs_total}</Text>
          <Text style={styles.statLabel}>Repairs</Text>
        </View>

        <View style={[styles.statCard, { backgroundColor: COLORS.successLight }]}>
          <Ionicons name="star" size={32} color={COLORS.success} />
          <Text style={styles.statValue}>{reportData.summary.customer_rating_avg}</Text>
          <Text style={styles.statLabel}>Rating</Text>
        </View>
      </View>

      {/* Performance Metrics */}
      <Card style={styles.card}>
        <Text style={styles.cardTitle}>Performance Metrics</Text>
        <View style={styles.progressRow}>
          <Text style={styles.label}>Completion Rate</Text>
          <View style={styles.progressBarContainer}>
            <View
              style={[
                styles.progressBar,
                { width: `${reportData.summary.completion_rate}%` },
              ]}
            />
          </View>
          <Text style={styles.percentText}>{reportData.summary.completion_rate}%</Text>
        </View>

        <View style={styles.infoRow}>
          <Text style={styles.label}>Avg Service Time:</Text>
          <Text style={styles.value}>{reportData.summary.avg_service_time}</Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Avg Callback Response:</Text>
          <Text style={styles.value}>{reportData.summary.avg_callback_response}</Text>
        </View>
        <View style={styles.infoRow}>
          <Text style={styles.label}>Total Materials Cost:</Text>
          <Text style={styles.valueError}>{reportData.summary.total_materials_cost}</Text>
        </View>
      </Card>
    </ScrollView>
  );

  const renderServicesTab = () => (
    <ScrollView>
      <Text style={styles.tabTitle}>
        Services ({reportData.summary.services_scheduled})
      </Text>
      {reportData.services.map((service, index) => (
        <Card key={index} style={styles.itemCard}>
          <View style={styles.itemHeader}>
            <Text style={styles.itemTitle}>Service #{service.sr_no}</Text>
            <Badge
              text={service.status}
              type={
                service.status === 'COMPLETED'
                  ? 'success'
                  : service.status === 'OVERDUE'
                  ? 'error'
                  : 'warning'
              }
            />
          </View>

          <View style={styles.itemRow}>
            <Ionicons name="calendar" size={16} color={COLORS.textSecondary} />
            <Text style={styles.itemText}>
              {service.scheduled_date} → {service.actual_date}
            </Text>
          </View>

          <View style={styles.itemRow}>
            <Ionicons name="person" size={16} color={COLORS.textSecondary} />
            <Text style={styles.itemText}>{service.technician_1}</Text>
          </View>

          {service.work_done !== '-' && (
            <View style={styles.itemRow}>
              <Ionicons name="clipboard" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText} numberOfLines={2}>
                {service.work_done}
              </Text>
            </View>
          )}

          {service.parts_replaced !== '-' && (
            <View style={styles.itemRow}>
              <Ionicons name="build" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>{service.parts_replaced}</Text>
            </View>
          )}

          {service.customer_rating !== '-' && (
            <View style={styles.itemRow}>
              <Ionicons name="star" size={16} color={COLORS.warning} />
              <Text style={styles.itemText}>{service.customer_rating}</Text>
            </View>
          )}
        </Card>
      ))}
    </ScrollView>
  );

  const renderCallbacksTab = () => (
    <ScrollView>
      <Text style={styles.tabTitle}>Callbacks ({reportData.summary.callbacks_total})</Text>
      {reportData.callbacks.length === 0 ? (
        <Card style={styles.emptyCard}>
          <Ionicons name="checkmark-circle" size={48} color={COLORS.success} />
          <Text style={styles.emptyText}>No callbacks in this period</Text>
        </Card>
      ) : (
        reportData.callbacks.map((callback, index) => (
          <Card key={index} style={styles.itemCard}>
            <View style={styles.itemHeader}>
              <Text style={styles.itemTitle}>Callback #{callback.sr_no}</Text>
              <Badge
                text={callback.status}
                type={callback.status === 'COMPLETED' ? 'success' : 'warning'}
              />
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="calendar" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>{callback.date}</Text>
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="alert-circle" size={16} color={COLORS.error} />
              <Text style={styles.itemText}>{callback.issue}</Text>
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="person" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>{callback.technicians}</Text>
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="time" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>
                Response: {callback.response_time} | Resolution: {callback.resolution_time}
              </Text>
            </View>

            {callback.materials_changed !== '-' && (
              <View style={styles.itemRow}>
                <Ionicons name="build" size={16} color={COLORS.textSecondary} />
                <Text style={styles.itemText}>{callback.materials_changed}</Text>
              </View>
            )}

            {callback.problem_solved !== '-' && (
              <View style={styles.itemRow}>
                <Ionicons name="checkmark-circle" size={16} color={COLORS.success} />
                <Text style={styles.itemText}>{callback.problem_solved}</Text>
              </View>
            )}
          </Card>
        ))
      )}
    </ScrollView>
  );

  const renderRepairsTab = () => (
    <ScrollView>
      <Text style={styles.tabTitle}>Repairs ({reportData.summary.repairs_total})</Text>
      {reportData.repairs.length === 0 ? (
        <Card style={styles.emptyCard}>
          <Ionicons name="checkmark-circle" size={48} color={COLORS.success} />
          <Text style={styles.emptyText}>No repairs in this period</Text>
        </Card>
      ) : (
        reportData.repairs.map((repair, index) => (
          <Card key={index} style={styles.itemCard}>
            <View style={styles.itemHeader}>
              <Text style={styles.itemTitle}>Repair #{repair.sr_no}</Text>
              <Badge
                text={repair.status}
                type={repair.status === 'COMPLETED' ? 'success' : 'warning'}
              />
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="calendar" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>{repair.date}</Text>
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="construct" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>{repair.type}</Text>
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="clipboard" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText} numberOfLines={2}>
                {repair.description}
              </Text>
            </View>

            <View style={styles.itemRow}>
              <Ionicons name="person" size={16} color={COLORS.textSecondary} />
              <Text style={styles.itemText}>{repair.technicians}</Text>
            </View>

            <View style={styles.costRow}>
              <Text style={styles.costLabel}>Total Cost:</Text>
              <Text style={styles.costValue}>{repair.total_cost}</Text>
            </View>
          </Card>
        ))
      )}
    </ScrollView>
  );

  const renderMaterialsTab = () => (
    <ScrollView>
      <Text style={styles.tabTitle}>
        Materials Used ({reportData.materials.length} items)
      </Text>

      <Card style={styles.card}>
        <Text style={styles.cardTitle}>Total Materials Cost</Text>
        <Text style={styles.totalCost}>{reportData.summary.total_materials_cost}</Text>
      </Card>

      {reportData.materials.map((material, index) => (
        <Card key={index} style={styles.itemCard}>
          <View style={styles.itemHeader}>
            <Text style={styles.itemTitle}>{material.material_name}</Text>
            <Text style={styles.materialCost}>{material.total_cost}</Text>
          </View>

          <View style={styles.itemRow}>
            <Ionicons name="cube" size={16} color={COLORS.textSecondary} />
            <Text style={styles.itemText}>
              {material.quantity} {material.unit}
            </Text>
          </View>

          <View style={styles.itemRow}>
            <Ionicons name="stats-chart" size={16} color={COLORS.textSecondary} />
            <Text style={styles.itemText}>
              Services: {material.used_in_services} | Callbacks: {material.used_in_callbacks} |
              Repairs: {material.used_in_repairs}
            </Text>
          </View>

          <View style={styles.itemRow}>
            <Ionicons name="calendar" size={16} color={COLORS.textSecondary} />
            <Text style={styles.itemText}>
              {material.first_used} - {material.last_used}
            </Text>
          </View>
        </Card>
      ))}
    </ScrollView>
  );

  return (
    <View style={styles.container}>
      <Header
        title="Customer AMC Report"
        showBack={true}
        onBackPress={() => navigation.goBack()}
      />

      <ScrollView contentContainerStyle={styles.content}>
        {/* Customer Selection */}
        <Card style={styles.card}>
          <Text style={styles.sectionTitle}>Select Customer</Text>
          <View style={styles.pickerContainer}>
            <Picker
              selectedValue={selectedCustomer}
              onValueChange={(value) => setSelectedCustomer(value)}
              style={styles.picker}
            >
              <Picker.Item label="Select a customer..." value="" />
              {customers.map((customer) => (
                <Picker.Item
                  key={customer.id}
                  label={`${customer.job_number} - ${customer.name}`}
                  value={customer.id}
                />
              ))}
            </Picker>
          </View>

          <TouchableOpacity
            style={styles.generateButton}
            onPress={generateReport}
            disabled={loading}
          >
            {loading ? (
              <ActivityIndicator color={COLORS.white} />
            ) : (
              <>
                <Ionicons name="document-text" size={20} color={COLORS.white} />
                <Text style={styles.generateButtonText}>Generate Report</Text>
              </>
            )}
          </TouchableOpacity>
        </Card>

        {/* Report Content */}
        {reportData && (
          <>
            {/* Customer Info Header */}
            <Card style={styles.card}>
              <Text style={styles.customerName}>{reportData.customer_info.customer_name}</Text>
              <Text style={styles.jobNumber}>{reportData.customer_info.job_number}</Text>
              <Text style={styles.area}>{reportData.customer_info.area}</Text>
            </Card>

            {/* Export Actions */}
            <View style={styles.actionsRow}>
              <TouchableOpacity style={styles.actionButton} onPress={shareReport}>
                <Ionicons name="share-social" size={20} color={COLORS.primary} />
                <Text style={styles.actionText}>Share</Text>
              </TouchableOpacity>

              <TouchableOpacity style={styles.actionButton} onPress={exportToPDF}>
                <Ionicons name="document" size={20} color={COLORS.error} />
                <Text style={styles.actionText}>PDF</Text>
              </TouchableOpacity>

              <TouchableOpacity style={styles.actionButton} onPress={exportToExcel}>
                <Ionicons name="grid" size={20} color={COLORS.success} />
                <Text style={styles.actionText}>Excel</Text>
              </TouchableOpacity>
            </View>

            {/* Tab Navigation */}
            <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.tabBar}>
              <TouchableOpacity
                style={[styles.tab, activeTab === 'summary' && styles.activeTab]}
                onPress={() => setActiveTab('summary')}
              >
                <Text
                  style={[styles.tabText, activeTab === 'summary' && styles.activeTabText]}
                >
                  Summary
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[styles.tab, activeTab === 'services' && styles.activeTab]}
                onPress={() => setActiveTab('services')}
              >
                <Text
                  style={[styles.tabText, activeTab === 'services' && styles.activeTabText]}
                >
                  Services ({reportData.summary.services_scheduled})
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[styles.tab, activeTab === 'callbacks' && styles.activeTab]}
                onPress={() => setActiveTab('callbacks')}
              >
                <Text
                  style={[styles.tabText, activeTab === 'callbacks' && styles.activeTabText]}
                >
                  Callbacks ({reportData.summary.callbacks_total})
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[styles.tab, activeTab === 'repairs' && styles.activeTab]}
                onPress={() => setActiveTab('repairs')}
              >
                <Text
                  style={[styles.tabText, activeTab === 'repairs' && styles.activeTabText]}
                >
                  Repairs ({reportData.summary.repairs_total})
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[styles.tab, activeTab === 'materials' && styles.activeTab]}
                onPress={() => setActiveTab('materials')}
              >
                <Text
                  style={[styles.tabText, activeTab === 'materials' && styles.activeTabText]}
                >
                  Materials ({reportData.materials.length})
                </Text>
              </TouchableOpacity>
            </ScrollView>

            {/* Tab Content */}
            <View style={styles.tabContent}>
              {activeTab === 'summary' && renderSummaryTab()}
              {activeTab === 'services' && renderServicesTab()}
              {activeTab === 'callbacks' && renderCallbacksTab()}
              {activeTab === 'repairs' && renderRepairsTab()}
              {activeTab === 'materials' && renderMaterialsTab()}
            </View>
          </>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    padding: SIZES.md,
  },
  card: {
    marginBottom: SIZES.md,
    padding: SIZES.md,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: SIZES.sm,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: SIZES.radiusSM,
    marginBottom: SIZES.md,
  },
  picker: {
    height: 50,
  },
  generateButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: SIZES.md,
    borderRadius: SIZES.radiusSM,
    gap: SIZES.xs,
  },
  generateButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  customerName: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SIZES.xs,
  },
  jobNumber: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '600',
    marginBottom: SIZES.xs,
  },
  area: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: SIZES.md,
  },
  actionButton: {
    alignItems: 'center',
    padding: SIZES.sm,
  },
  actionText: {
    marginTop: SIZES.xs,
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  tabBar: {
    marginBottom: SIZES.md,
  },
  tab: {
    paddingVertical: SIZES.sm,
    paddingHorizontal: SIZES.md,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    marginRight: SIZES.sm,
  },
  activeTab: {
    borderBottomColor: COLORS.primary,
  },
  tabText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontWeight: '500',
  },
  activeTabText: {
    color: COLORS.primary,
    fontWeight: '700',
  },
  tabContent: {
    minHeight: 400,
  },
  tabTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SIZES.md,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: SIZES.md,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SIZES.xs,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey100,
  },
  label: {
    fontSize: 14,
    color: COLORS.textSecondary,
    flex: 1,
  },
  value: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
    flex: 1,
    textAlign: 'right',
  },
  valueSuccess: {
    fontSize: 14,
    color: COLORS.success,
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  valueError: {
    fontSize: 14,
    color: COLORS.error,
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SIZES.md,
  },
  statCard: {
    width: '48%',
    padding: SIZES.md,
    borderRadius: SIZES.radiusSM,
    alignItems: 'center',
    marginBottom: SIZES.sm,
    ...SHADOWS.small,
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginTop: SIZES.xs,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: SIZES.xs,
  },
  progressRow: {
    marginBottom: SIZES.md,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: COLORS.grey100,
    borderRadius: 4,
    marginVertical: SIZES.xs,
  },
  progressBar: {
    height: '100%',
    backgroundColor: COLORS.success,
    borderRadius: 4,
  },
  percentText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.success,
    textAlign: 'right',
  },
  itemCard: {
    marginBottom: SIZES.md,
    padding: SIZES.md,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.sm,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: SIZES.xs,
    gap: SIZES.xs,
  },
  itemText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    flex: 1,
  },
  costRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: SIZES.sm,
    paddingTop: SIZES.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.grey100,
  },
  costLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },
  costValue: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.error,
  },
  emptyCard: {
    alignItems: 'center',
    padding: SIZES.xl,
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginTop: SIZES.md,
  },
  totalCost: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.error,
    textAlign: 'center',
  },
  materialCost: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.error,
  },
});

export default CustomerAMCReportScreen;
