import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Share,
} from 'react-native';
import { useSelector } from 'react-redux';
import { Ionicons } from '@expo/vector-icons';
import { Picker } from '@react-native-picker/picker';
import { Card, Header } from '../../components/common';
import { COLORS, SIZES, SHADOWS } from '../../constants/theme';
import { API_CONFIG } from '../../constants';

const TechnicianReportScreen = ({ navigation }) => {
  const { token } = useSelector((state) => state.auth);
  const [loading, setLoading] = useState(false);
  const [technicians, setTechnicians] = useState([]);
  const [selectedTechnician, setSelectedTechnician] = useState('');
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [reportData, setReportData] = useState(null);

  const months = [
    { label: 'January', value: 1 },
    { label: 'February', value: 2 },
    { label: 'March', value: 3 },
    { label: 'April', value: 4 },
    { label: 'May', value: 5 },
    { label: 'June', value: 6 },
    { label: 'July', value: 7 },
    { label: 'August', value: 8 },
    { label: 'September', value: 9 },
    { label: 'October', value: 10 },
    { label: 'November', value: 11 },
    { label: 'December', value: 12 },
  ];

  const years = [2023, 2024, 2025, 2026];

  useEffect(() => {
    fetchTechnicians();
  }, []);

  const fetchTechnicians = async () => {
    try {
      const response = await fetch(`${API_CONFIG.BASE_URL}/admin/technicians`, {
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const data = await response.json();
        setTechnicians(data);
        if (data.length > 0) {
          setSelectedTechnician(data[0].id);
        }
      }
    } catch (error) {
      console.error('Error fetching technicians:', error);
    }
  };

  const generateReport = async () => {
    if (!selectedTechnician) {
      Alert.alert('Error', 'Please select a technician');
      return;
    }

    setLoading(true);
    try {
      const response = await fetch(
        `${API_CONFIG.BASE_URL}/reports/technician-performance/${selectedTechnician}?month=${selectedMonth}&year=${selectedYear}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
        }
      );

      if (response.ok) {
        const data = await response.json();
        setReportData(data);
      } else {
        const error = await response.json();
        Alert.alert('Error', error.detail || 'Failed to generate report');
      }
    } catch (error) {
      console.error('Error generating report:', error);
      Alert.alert('Error', 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const shareReport = async () => {
    if (!reportData) return;

    try {
      const message = `
${reportData.technician_info.name} - Performance Report

Period: ${reportData.period.month} ${reportData.period.year}

Services Assigned: ${reportData.summary.total_assigned}
Completed: ${reportData.summary.completed} (${reportData.summary.completion_rate}%)
Callbacks: ${reportData.summary.callbacks_attended}
Repairs: ${reportData.summary.repairs_done}

Working Hours: ${reportData.summary.total_working_hours} hours
Customer Rating: ${reportData.summary.customer_rating}/5.0
On-Time: ${reportData.summary.on_time_percentage}%

Generated by LegendLift
      `.trim();

      await Share.share({ message });
    } catch (error) {
      console.error('Error sharing report:', error);
    }
  };

  return (
    <View style={styles.container}>
      <Header
        title="Technician Performance"
        showBack={true}
        onBackPress={() => navigation.goBack()}
      />

      <ScrollView contentContainerStyle={styles.content}>
        {/* Selection Card */}
        <Card style={styles.card}>
          <Text style={styles.sectionTitle}>Select Technician</Text>
          <View style={styles.pickerContainer}>
            <Picker
              selectedValue={selectedTechnician}
              onValueChange={(value) => setSelectedTechnician(value)}
              style={styles.picker}
            >
              <Picker.Item label="Select a technician..." value="" />
              {technicians.map((tech) => (
                <Picker.Item key={tech.id} label={tech.name} value={tech.id} />
              ))}
            </Picker>
          </View>

          <View style={styles.dateRow}>
            <View style={styles.datePickerHalf}>
              <Text style={styles.label}>Month</Text>
              <View style={styles.pickerContainer}>
                <Picker
                  selectedValue={selectedMonth}
                  onValueChange={(value) => setSelectedMonth(value)}
                  style={styles.picker}
                >
                  {months.map((month) => (
                    <Picker.Item key={month.value} label={month.label} value={month.value} />
                  ))}
                </Picker>
              </View>
            </View>

            <View style={styles.datePickerHalf}>
              <Text style={styles.label}>Year</Text>
              <View style={styles.pickerContainer}>
                <Picker
                  selectedValue={selectedYear}
                  onValueChange={(value) => setSelectedYear(value)}
                  style={styles.picker}
                >
                  {years.map((year) => (
                    <Picker.Item key={year} label={year.toString()} value={year} />
                  ))}
                </Picker>
              </View>
            </View>
          </View>

          <TouchableOpacity
            style={styles.generateButton}
            onPress={generateReport}
            disabled={loading}
          >
            {loading ? (
              <ActivityIndicator color={COLORS.white} />
            ) : (
              <>
                <Ionicons name="analytics" size={20} color={COLORS.white} />
                <Text style={styles.generateButtonText}>Generate Report</Text>
              </>
            )}
          </TouchableOpacity>
        </Card>

        {/* Report Content */}
        {reportData && (
          <>
            {/* Technician Info Header */}
            <Card style={styles.card}>
              <Text style={styles.technicianName}>{reportData.technician_info.name}</Text>
              <Text style={styles.technicianEmail}>{reportData.technician_info.email}</Text>
              <Text style={styles.period}>
                {reportData.period.month} {reportData.period.year}
              </Text>
            </Card>

            {/* Share Button */}
            <TouchableOpacity style={styles.shareButton} onPress={shareReport}>
              <Ionicons name="share-social" size={20} color={COLORS.white} />
              <Text style={styles.shareButtonText}>Share Report</Text>
            </TouchableOpacity>

            {/* Performance Summary Grid */}
            <View style={styles.statsGrid}>
              <View style={[styles.statCard, { backgroundColor: COLORS.primaryLight }]}>
                <Ionicons name="list" size={32} color={COLORS.primary} />
                <Text style={styles.statValue}>{reportData.summary.total_assigned}</Text>
                <Text style={styles.statLabel}>Assigned</Text>
              </View>

              <View style={[styles.statCard, { backgroundColor: COLORS.successLight }]}>
                <Ionicons name="checkmark-circle" size={32} color={COLORS.success} />
                <Text style={styles.statValue}>{reportData.summary.completed}</Text>
                <Text style={styles.statLabel}>Completed</Text>
              </View>

              <View style={[styles.statCard, { backgroundColor: COLORS.warningLight }]}>
                <Ionicons name="time" size={32} color={COLORS.warning} />
                <Text style={styles.statValue}>{reportData.summary.pending}</Text>
                <Text style={styles.statLabel}>Pending</Text>
              </View>

              <View style={[styles.statCard, { backgroundColor: COLORS.infoLight }]}>
                <Ionicons name="call" size={32} color={COLORS.info} />
                <Text style={styles.statValue}>{reportData.summary.callbacks_attended}</Text>
                <Text style={styles.statLabel}>Callbacks</Text>
              </View>

              <View style={[styles.statCard, { backgroundColor: COLORS.secondaryLight }]}>
                <Ionicons name="construct" size={32} color={COLORS.secondary} />
                <Text style={styles.statValue}>{reportData.summary.repairs_done}</Text>
                <Text style={styles.statLabel}>Repairs</Text>
              </View>

              <View style={[styles.statCard, { backgroundColor: COLORS.successLight }]}>
                <Ionicons name="star" size={32} color={COLORS.warning} />
                <Text style={styles.statValue}>{reportData.summary.customer_rating}</Text>
                <Text style={styles.statLabel}>Rating</Text>
              </View>
            </View>

            {/* Performance Metrics */}
            <Card style={styles.card}>
              <Text style={styles.cardTitle}>Performance Metrics</Text>

              <View style={styles.progressRow}>
                <Text style={styles.label}>Completion Rate</Text>
                <View style={styles.progressBarContainer}>
                  <View
                    style={[
                      styles.progressBar,
                      { width: `${reportData.summary.completion_rate}%` },
                    ]}
                  />
                </View>
                <Text style={styles.percentText}>{reportData.summary.completion_rate}%</Text>
              </View>

              <View style={styles.progressRow}>
                <Text style={styles.label}>On-Time Performance</Text>
                <View style={styles.progressBarContainer}>
                  <View
                    style={[
                      styles.progressBar,
                      {
                        width: `${reportData.summary.on_time_percentage}%`,
                        backgroundColor: COLORS.info,
                      },
                    ]}
                  />
                </View>
                <Text style={styles.percentText}>{reportData.summary.on_time_percentage}%</Text>
              </View>

              <View style={styles.infoRow}>
                <Text style={styles.label}>Total Working Hours:</Text>
                <Text style={styles.value}>{reportData.summary.total_working_hours} hrs</Text>
              </View>

              <View style={styles.infoRow}>
                <Text style={styles.label}>Avg Service Time:</Text>
                <Text style={styles.value}>{reportData.summary.avg_service_time}</Text>
              </View>

              <View style={styles.infoRow}>
                <Text style={styles.label}>Services Per Day:</Text>
                <Text style={styles.value}>{reportData.services_per_day}</Text>
              </View>

              <View style={styles.infoRow}>
                <Text style={styles.label}>Unique Customers:</Text>
                <Text style={styles.value}>{reportData.unique_customers_served}</Text>
              </View>

              <View style={styles.infoRow}>
                <Text style={styles.label}>5-Star Ratings:</Text>
                <Text style={styles.valueSuccess}>{reportData.summary.five_star_count}</Text>
              </View>

              <View style={styles.infoRow}>
                <Text style={styles.label}>On-Time Services:</Text>
                <Text style={styles.valueSuccess}>{reportData.summary.on_time_services}</Text>
              </View>
            </Card>

            {/* Route Coverage */}
            <Card style={styles.card}>
              <Text style={styles.cardTitle}>Route Coverage</Text>
              {Object.keys(reportData.route_coverage).length === 0 ? (
                <Text style={styles.emptyText}>No route data available</Text>
              ) : (
                Object.entries(reportData.route_coverage).map(([route, count]) => (
                  <View key={route} style={styles.routeRow}>
                    <View style={styles.routeBadge}>
                      <Ionicons name="location" size={16} color={COLORS.primary} />
                      <Text style={styles.routeText}>{route}</Text>
                    </View>
                    <Text style={styles.routeCount}>{count} services</Text>
                  </View>
                ))
              )}
            </Card>

            {/* Performance Summary */}
            <Card style={styles.summaryCard}>
              <View style={styles.summaryHeader}>
                <Ionicons name="trophy" size={32} color={COLORS.warning} />
                <Text style={styles.summaryTitle}>Overall Performance</Text>
              </View>

              <View style={styles.summaryGrid}>
                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>
                    {reportData.summary.completion_rate}%
                  </Text>
                  <Text style={styles.summaryLabel}>Completion</Text>
                </View>

                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>{reportData.summary.customer_rating}</Text>
                  <Text style={styles.summaryLabel}>Rating</Text>
                </View>

                <View style={styles.summaryItem}>
                  <Text style={styles.summaryValue}>
                    {reportData.summary.on_time_percentage}%
                  </Text>
                  <Text style={styles.summaryLabel}>On-Time</Text>
                </View>
              </View>

              <Text style={styles.summaryDescription}>
                {reportData.summary.completion_rate >= 90
                  ? '🎉 Excellent Performance! Keep up the great work!'
                  : reportData.summary.completion_rate >= 75
                  ? '👍 Good Performance! Room for improvement.'
                  : '⚠️ Needs Improvement. Focus on completion rate.'}
              </Text>
            </Card>
          </>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    padding: SIZES.md,
  },
  card: {
    marginBottom: SIZES.md,
    padding: SIZES.md,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: SIZES.sm,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: SIZES.radiusSM,
    marginBottom: SIZES.md,
  },
  picker: {
    height: 50,
  },
  dateRow: {
    flexDirection: 'row',
    gap: SIZES.sm,
    marginBottom: SIZES.md,
  },
  datePickerHalf: {
    flex: 1,
  },
  label: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: SIZES.xs,
  },
  generateButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: SIZES.md,
    borderRadius: SIZES.radiusSM,
    gap: SIZES.xs,
  },
  generateButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  technicianName: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SIZES.xs,
  },
  technicianEmail: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: SIZES.xs,
  },
  period: {
    fontSize: 16,
    color: COLORS.primary,
    fontWeight: '600',
  },
  shareButton: {
    backgroundColor: COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: SIZES.md,
    borderRadius: SIZES.radiusSM,
    marginBottom: SIZES.md,
    gap: SIZES.xs,
  },
  shareButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SIZES.md,
  },
  statCard: {
    width: '48%',
    padding: SIZES.md,
    borderRadius: SIZES.radiusSM,
    alignItems: 'center',
    marginBottom: SIZES.sm,
    ...SHADOWS.small,
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginTop: SIZES.xs,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: SIZES.xs,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textPrimary,
    marginBottom: SIZES.md,
  },
  progressRow: {
    marginBottom: SIZES.md,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: COLORS.grey100,
    borderRadius: 4,
    marginVertical: SIZES.xs,
  },
  progressBar: {
    height: '100%',
    backgroundColor: COLORS.success,
    borderRadius: 4,
  },
  percentText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.success,
    textAlign: 'right',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SIZES.xs,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey100,
  },
  value: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  valueSuccess: {
    fontSize: 14,
    color: COLORS.success,
    fontWeight: '600',
  },
  routeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: SIZES.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grey100,
  },
  routeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.xs,
  },
  routeText: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  routeCount: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  emptyText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    paddingVertical: SIZES.lg,
  },
  summaryCard: {
    marginBottom: SIZES.md,
    padding: SIZES.lg,
    backgroundColor: COLORS.primaryLight,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SIZES.sm,
    marginBottom: SIZES.md,
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  summaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: SIZES.md,
  },
  summaryItem: {
    alignItems: 'center',
  },
  summaryValue: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.primary,
  },
  summaryLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: SIZES.xs,
  },
  summaryDescription: {
    fontSize: 14,
    color: COLORS.textPrimary,
    textAlign: 'center',
    fontWeight: '500',
  },
});

export default TechnicianReportScreen;
